[package]
authors = ["Mathieu Amiot <m.amiot@otak-arts.com>"]
name = "ocl-image-resizer"
version = "0.1.0"

[dependencies]
actix = "0.5.6"
actix-web = "0.6.5"
env_logger = "0.5.10"
futures = "0.2.1"
image = "0.19.0"
log = "0.4.1"
ocl = "0.18.0"
